version: 2.1

orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: default

    steps:
      # Ensure code is checked out
      - checkout

      # Ensure gradlew has execution permissions
      - run:
          name: Set executable permissions for gradlew
          command: chmod +x ./gradlew

      # The next step will run the unit tests
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      # Start the emulator and run the Instrumentation tests
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

      # Assemble the release build
      - run:
          name: Assemble release build
          command: ./gradlew assembleRelease

workflows:
  sample:
    jobs:
      - build-and-test
